// src/shared/ui/Button.svelte
<script lang="ts">
  import { Loader2 } from '@lucide/svelte'
  import type { Snippet } from 'svelte'
  import type { HTMLButtonAttributes } from 'svelte/elements'
  import { cn } from '@/shared/lib'

  type Variant = 'primary' | 'secondary' | 'ghost' | 'destructive'
  type Size = 'sm' | 'md'

  interface Props extends HTMLButtonAttributes {
    variant?: Variant
    size?: Size
    loading?: boolean
    icon?: Snippet
    children?: Snippet
    class?: string
  }

  let {
    variant = 'primary',
    size = 'md',
    loading = false,
    icon,
    children,
    class: className,
    disabled,
    ...rest
  }: Props = $props()

  const variantClasses: Record<Variant, string> = {
    primary: 'bg-primary text-primary-foreground shadow-xs hover:bg-primary/90',
    secondary:
      'border border-border bg-surface text-foreground hover:bg-surface-hover',
    ghost: 'text-foreground hover:bg-surface-hover',
    destructive:
      'bg-destructive text-destructive-foreground shadow-xs hover:bg-destructive/90',
  }

  const sizeClasses: Record<Size, string> = {
    sm: 'h-8 gap-1.5 px-2.5 text-xs',
    md: 'h-9 gap-2 px-3 text-sm',
  }
</script>

<button
  class={cn(
    'inline-flex items-center justify-center rounded-lg font-medium transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-primary/40 disabled:pointer-events-none disabled:opacity-50',
    variantClasses[variant],
    sizeClasses[size],
    className,
  )}
  disabled={disabled || loading}
  {...rest}
>
  {#if loading}
    <Loader2 class="size-4 animate-spin" />
  {:else if icon}
    {@render icon()}
  {/if}
  {#if children}{@render children()}{/if}
</button>

// src/shared/ui/button.tsx
import { Loader2 } from 'lucide-react'
import type { ButtonHTMLAttributes, ReactNode } from 'react'

import { cn } from '@/shared/lib/utils'

type Variant = 'primary' | 'secondary' | 'ghost' | 'destructive'
type Size = 'sm' | 'md'

interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: Variant
  size?: Size
  loading?: boolean
  icon?: ReactNode
}

const variantClasses: Record<Variant, string> = {
  primary: 'bg-primary text-primary-foreground shadow-xs hover:bg-primary/90',
  secondary:
    'border border-border bg-surface text-foreground hover:bg-surface-hover',
  ghost: 'text-foreground hover:bg-surface-hover',
  destructive:
    'bg-destructive text-destructive-foreground shadow-xs hover:bg-destructive/90',
}

const sizeClasses: Record<Size, string> = {
  sm: 'h-8 gap-1.5 px-2.5 text-xs',
  md: 'h-9 gap-2 px-3 text-sm',
}

export const Button = ({
  variant = 'primary',
  size = 'md',
  loading = false,
  icon,
  className,
  children,
  disabled,
  ...props
}: ButtonProps) => (
  <button
    className={cn(
      'inline-flex items-center justify-center rounded-lg font-medium transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-primary/40 disabled:pointer-events-none disabled:opacity-50',
      variantClasses[variant],
      sizeClasses[size],
      className,
    )}
    disabled={disabled || loading}
    {...props}
  >
    {loading ? <Loader2 className="size-4 animate-spin" /> : icon}
    {children}
  </button>
)
