// src/shared/ui/Checkbox.svelte
<script lang="ts">
  import type { HTMLInputAttributes } from 'svelte/elements'
  import { cn } from '@/shared/lib'

  interface Props extends HTMLInputAttributes {
    class?: string
  }

  let { class: className, ...rest }: Props = $props()
</script>

<input class={cn('size-4 rounded border-border accent-primary', className)} type="checkbox" {...rest} />

// src/shared/ui/checkbox.tsx
import type { InputHTMLAttributes } from 'react'

import { cn } from '@/shared/lib/utils'

export const Checkbox = ({
  className,
  ...props
}: InputHTMLAttributes<HTMLInputElement>) => (
  <input
    className={cn('size-4 rounded border-border accent-primary', className)}
    type="checkbox"
    {...props}
  />
)
