// src/shared/ui/input.tsx
import type { InputHTMLAttributes } from 'react'

import { cn } from '@/shared/lib/utils'

export const Input = ({
  className,
  ...props
}: InputHTMLAttributes<HTMLInputElement>) => (
  <input
    className={cn(
      'h-9 w-full rounded-lg border border-border bg-surface px-3 text-sm text-foreground placeholder:text-muted-foreground focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/25',
      className,
    )}
    {...props}
  />
)

// src/shared/ui/input/input.svelte
<script lang="ts">
  import type { HTMLInputAttributes } from 'svelte/elements'
  import { cn } from '@/shared/lib/utils'

  let {
    class: className,
    value = $bindable(),
    ...restProps
  }: HTMLInputAttributes = $props()
</script>

<input
  bind:value
  class={cn(
    'flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm transition-colors placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring/40 disabled:cursor-not-allowed disabled:opacity-50',
    className,
  )}
  {...restProps}
/>
